version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pandas
            pip install matplotlib
            pip install numpy
      - run:
          name: Run tests
          command: pytest

workflows:
  version: 2
  build:
    jobs:
      - build